"""F7 configurable laboratory analyses, agenda, and compliance."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = "0009_f7_laboratory"
down_revision = "0008_f6_readonly_plc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    uuid = postgresql.UUID(as_uuid=True)
    timestamp_columns = [sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now())]
    op.create_table("laboratorio_unidad", sa.Column("id", uuid, primary_key=True), sa.Column("codigo", sa.String(30), unique=True, nullable=False), sa.Column("descripcion", sa.String(120), nullable=False), sa.Column("activo", sa.Boolean(), nullable=False, server_default=sa.true()), *timestamp_columns)
    op.create_table("laboratorio_punto_muestreo", sa.Column("id", uuid, primary_key=True), sa.Column("codigo", sa.String(40), unique=True, nullable=False), sa.Column("descripcion", sa.String(160), nullable=False), sa.Column("sector", sa.String(40), nullable=False), sa.Column("activo", sa.Boolean(), nullable=False, server_default=sa.true()), *timestamp_columns)
    op.create_table("laboratorio_determinacion", sa.Column("id", uuid, primary_key=True), sa.Column("codigo", sa.String(40), unique=True, nullable=False), sa.Column("descripcion", sa.String(160), nullable=False), sa.Column("tipo_resultado", sa.String(20), nullable=False), sa.Column("activo", sa.Boolean(), nullable=False, server_default=sa.true()), *timestamp_columns, sa.CheckConstraint("tipo_resultado IN ('NUMERICO', 'GRANULOMETRIA')", name="ck_lab_determinacion_tipo"))
    op.create_table("laboratorio_punto_determinacion", sa.Column("id", uuid, primary_key=True), sa.Column("id_punto", uuid, sa.ForeignKey("laboratorio_punto_muestreo.id", ondelete="RESTRICT"), nullable=False), sa.Column("id_determinacion", uuid, sa.ForeignKey("laboratorio_determinacion.id", ondelete="RESTRICT"), nullable=False), sa.Column("id_unidad", uuid, sa.ForeignKey("laboratorio_unidad.id", ondelete="RESTRICT"), nullable=False), sa.Column("id_limite", sa.String(10), sa.ForeignKey("limite.id", ondelete="RESTRICT")), sa.Column("vigente_desde", sa.Date(), nullable=False), sa.Column("vigente_hasta_exclusiva", sa.Date()), sa.Column("activo", sa.Boolean(), nullable=False, server_default=sa.true()), *timestamp_columns, sa.CheckConstraint("vigente_hasta_exclusiva IS NULL OR vigente_hasta_exclusiva > vigente_desde", name="ck_lab_punto_determinacion_intervalo"))
    op.create_index("ix_lab_punto_determinacion_vigencia", "laboratorio_punto_determinacion", ["id_punto", "vigente_desde"])
    op.create_table("laboratorio_frecuencia_control", sa.Column("id", uuid, primary_key=True), sa.Column("id_configuracion", uuid, sa.ForeignKey("laboratorio_punto_determinacion.id", ondelete="RESTRICT"), nullable=False), sa.Column("vigente_desde", sa.DateTime(timezone=True), nullable=False), sa.Column("vigente_hasta_exclusiva", sa.DateTime(timezone=True)), sa.Column("intervalo_horas", sa.Numeric(8, 2), nullable=False), sa.Column("activo", sa.Boolean(), nullable=False, server_default=sa.true()), *timestamp_columns, sa.CheckConstraint("intervalo_horas > 0", name="ck_lab_frecuencia_intervalo"), sa.CheckConstraint("vigente_hasta_exclusiva IS NULL OR vigente_hasta_exclusiva > vigente_desde", name="ck_lab_frecuencia_vigencia"))
    op.create_index("ix_lab_frecuencia_vigencia", "laboratorio_frecuencia_control", ["id_configuracion", "vigente_desde"])
    op.create_table("laboratorio_tamiz", sa.Column("id", uuid, primary_key=True), sa.Column("torre", sa.String(80), nullable=False), sa.Column("codigo", sa.String(40), unique=True, nullable=False), sa.Column("descripcion", sa.String(160), nullable=False), sa.Column("activo", sa.Boolean(), nullable=False, server_default=sa.true()), *timestamp_columns)
    op.create_table("laboratorio_configuracion_tamiz", sa.Column("id", uuid, primary_key=True), sa.Column("id_configuracion", uuid, sa.ForeignKey("laboratorio_punto_determinacion.id", ondelete="CASCADE"), nullable=False), sa.Column("id_tamiz", uuid, sa.ForeignKey("laboratorio_tamiz.id", ondelete="RESTRICT"), nullable=False), sa.UniqueConstraint("id_configuracion", "id_tamiz", name="uq_lab_configuracion_tamiz"))
    op.create_table("analisis_laboratorio", sa.Column("id", uuid, primary_key=True), sa.Column("client_uuid", uuid, unique=True, nullable=False), sa.Column("id_punto", uuid, sa.ForeignKey("laboratorio_punto_muestreo.id", ondelete="RESTRICT"), nullable=False), sa.Column("fecha_operativa", sa.Date(), nullable=False), sa.Column("turno_codigo", sa.String(30), nullable=False), sa.Column("instante_muestreo", sa.DateTime(timezone=True), nullable=False), sa.Column("id_mua", uuid, sa.ForeignKey("mua.id", ondelete="RESTRICT")), sa.Column("id_registro_stock", uuid, sa.ForeignKey("registro_operativo.id", ondelete="RESTRICT")), sa.Column("id_registro_proceso", uuid, sa.ForeignKey("registro_operativo.id", ondelete="RESTRICT")), sa.Column("silo", sa.Integer()), sa.Column("id_producto", uuid, sa.ForeignKey("catalogo.id", ondelete="RESTRICT")), sa.Column("estado", sa.String(20), nullable=False, server_default="BORRADOR"), sa.Column("revision", sa.Integer(), nullable=False, server_default="1"), sa.Column("creado_por", uuid, sa.ForeignKey("usuario.id", ondelete="RESTRICT"), nullable=False), sa.Column("motivo_correccion", sa.String(300)), *timestamp_columns, sa.CheckConstraint("silo IS NULL OR silo BETWEEN 1 AND 16", name="ck_analisis_laboratorio_silo"), sa.CheckConstraint("estado IN ('BORRADOR', 'CERRADO', 'VALIDADO', 'ANULADO')", name="ck_analisis_laboratorio_estado"), sa.CheckConstraint("revision > 0", name="ck_analisis_laboratorio_revision"))
    op.create_index("ix_analisis_laboratorio_consulta", "analisis_laboratorio", ["id_punto", "fecha_operativa"])
    op.create_table("analisis_laboratorio_resultado", sa.Column("id", uuid, primary_key=True), sa.Column("id_analisis", uuid, sa.ForeignKey("analisis_laboratorio.id", ondelete="CASCADE"), nullable=False), sa.Column("id_configuracion", uuid, sa.ForeignKey("laboratorio_punto_determinacion.id", ondelete="RESTRICT"), nullable=False), sa.Column("valor", sa.Numeric(16, 5)), sa.Column("unidad", sa.String(30), nullable=False), sa.UniqueConstraint("id_analisis", "id_configuracion", name="uq_analisis_laboratorio_resultado"))
    op.create_table("analisis_granulometria", sa.Column("id", uuid, primary_key=True), sa.Column("id_analisis", uuid, sa.ForeignKey("analisis_laboratorio.id", ondelete="CASCADE"), nullable=False), sa.Column("id_configuracion", uuid, sa.ForeignKey("laboratorio_punto_determinacion.id", ondelete="RESTRICT"), nullable=False), sa.Column("id_tamiz", uuid, sa.ForeignKey("laboratorio_tamiz.id", ondelete="RESTRICT"), nullable=False), sa.Column("valor", sa.Numeric(16, 5), nullable=False), sa.UniqueConstraint("id_analisis", "id_configuracion", "id_tamiz", name="uq_analisis_granulometria"))
    op.create_table("evento_desvio_laboratorio", sa.Column("id", uuid, primary_key=True), sa.Column("id_resultado", uuid, sa.ForeignKey("analisis_laboratorio_resultado.id", ondelete="RESTRICT"), nullable=False), sa.Column("id_limite", sa.String(10), sa.ForeignKey("limite.id", ondelete="RESTRICT"), nullable=False), sa.Column("id_limite_version", uuid, sa.ForeignKey("limite_version.id", ondelete="RESTRICT"), nullable=False), sa.Column("id_desvio", sa.String(10), sa.ForeignKey("plan_reaccion.id_desvio", ondelete="RESTRICT"), nullable=False), sa.Column("estado", sa.String(20), nullable=False, server_default="ABIERTO"), sa.Column("valor_actual", sa.Numeric(16, 5), nullable=False), *timestamp_columns, sa.UniqueConstraint("id_resultado", "id_limite_version", name="uq_desvio_laboratorio_resultado_version"), sa.CheckConstraint("estado IN ('ABIERTO', 'EN_TRATAMIENTO', 'VERIFICADO', 'VENCIDO', 'ESCALADO', 'CERRADO', 'INVALIDADO')", name="ck_evento_desvio_laboratorio_estado"))


def downgrade() -> None:
    for table in ("evento_desvio_laboratorio", "analisis_granulometria", "analisis_laboratorio_resultado", "analisis_laboratorio", "laboratorio_configuracion_tamiz", "laboratorio_tamiz", "laboratorio_frecuencia_control", "laboratorio_punto_determinacion", "laboratorio_determinacion", "laboratorio_punto_muestreo", "laboratorio_unidad"):
        op.drop_table(table)
